export const tuits = [
    { 
        "_id": 123,
        "topic": "Space", 
        "userName": "Tesla",
        "title": "Tesla Cybertruck lands on Mars and picks up the Curiosity rover on its 6' bed",
        "time": "2h",   
        "image": require("../../images/tesla-icon.png"),
        "liked": "false",
        "replies": "1",
        "retuits": "2",
        "likes": "3",
        "handle": "@tesla",
        "tuit": "This is a Tesla tuit!",
    },
    { 
        "_id": 234,
        "topic": "Space",
        "userName": "SpaceX",
        "title": "100s of SpaceX Starships land on Mars after a 6 month journey. 1000s of Martian colonists being building Mars Base 1",
        "time": "2h",
        "image": require("../../images/spacex-icon.jpeg"),
        "liked": "true",
        "replies": "419",
        "retuits": "534",
        "likes": "607",
        "handle": "@spacex",
        "tuit": "This is a SpaceX tuit!",
    },
    { 
        "_id": 456,
        "topic": "Energy",
        "userName": "Tesla",
        "title": "Tesla FSD finally makes driving obsolete. After years of delay, Tesla Full Self Driving can drive you to work while you work, play, or sleep",
        "time": "4d",
        "image": require("../../images/tesla-icon.png"),
        "liked": "false",
        "replies": "7",
        "retuits": "8",
        "likes": "9",
        "handle": "@tesla",
        "tuit": "This is another Tesla tuit!",
        "id": "2"  
    },
    {
        "_id": 789,
        "topic": "Space",
        "userName": "SpaceX",
        "time": "2h",
        "title": "100s of SpaceX Starships land on Mars after a 6 month journey. 1000s of Martian colonists being building Mars Base 1",
        "image": require("../../images/spacex-icon.jpeg"),
        "liked": "true",
        "replies": 123,
        "retuits": 432,
        "likes": 2345,
        "handle": "@spacex",
        "tuit": "You want to wake up in the morning and think the future is going to be great - and that’s what being a spacefaring civilization is all about. It’s about believing in the future and thinking that the future will be better than the past. And I can’t think of anything more exciting than going out there and being among the stars",
    },
]